USE [Nidan]
GO

/****** Object:  Table [dbo].[EventDay]    Script Date: 21/12/2016 14:36:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EventDay](
	[SrNo] [int] IDENTITY(1,1) NOT NULL,
	[Activity] [varchar](max) NOT NULL,
	[Completed] [varchar](100) NOT NULL,
	[ReferenceDetailDocument] [varchar](max) NOT NULL,
 CONSTRAINT [PK_EventDay] PRIMARY KEY CLUSTERED 
(
	[SrNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


