USE [Nidan]
GO

/****** Object:  Table [dbo].[EventActivity]    Script Date: 17/12/2016 03:08:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EventActivity](
	[EventActvityId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](500) NULL,
	[Sequence] [int] NULL,
 CONSTRAINT [PK_EventActivity] PRIMARY KEY CLUSTERED 
(
	[EventActvityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


